### ISSUE TITLE
Error with "Insert column" and empty columns

### ISSUE THREAD

**Issue by Alexey-T** [Artem3213212/cuda_csv_hilite#5]
@OlehL 
file
```
aa,bb,cc
aa,,cc
aa,bb,cc
```
каретка на колонке bb.
изза пустой колонки получается креш при `Insert column righer` (я переименовал команды).
```
Startup: total: 800ms, including plugins: 40ms
Python 3.6.8
Loading toolbar config
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.config/cudatext/py/cuda_csv_hilite/__init__.py", line 310, in rnew_col
    self.current_col_do('rnew')
  File "/home/user/.config/cudatext/py/cuda_csv_hilite/__init__.py", line 243, in current_col_do
    _csv = parse_csv_line_as_dict(line, sep=option_separator)
  File "/home/user/.config/cudatext/py/cuda_csv_hilite/csv_proc.py", line 64, in parse_csv_line_as_dict
    res[col][1] += 1
KeyError: 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.config/cudatext/py/cuda_csv_hilite/__init__.py", line 310, in rnew_col
    self.current_col_do('rnew')
  File "/home/user/.config/cudatext/py/cuda_csv_hilite/__init__.py", line 243, in current_col_do
    _csv = parse_csv_line_as_dict(line, sep=option_separator)
  File "/home/user/.config/cudatext/py/cuda_csv_hilite/csv_proc.py", line 64, in parse_csv_line_as_dict
    res[col][1] += 1
KeyError: 2
```

**Comment by OlehL** [comment]
исправление в моем гите
если все ок, сделаю пулреквест

**Comment by Alexey-T** [comment]
Можешь делать
